version: "3"

services:
  api:
    # image: node:alpine
    build: .
    volumes:
      - ./:/usr/src/api
    working_dir: /usr/src/api
    ports:
      - 3000:3000
    command: sh -c "yarn install && adonis migration:run && aglio -i API.apib -o api.html && adonis serve --dev"
